# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\OneDrive\python入坟\学习ing\qt-designer\project1-slide menu\UI_window\Main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1099, 572)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 73, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 61, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(29, 32, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 73, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 61, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(29, 32, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 73, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 61, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(29, 32, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet("/* LINE EDIT */\n"
"QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* SCROLL BARS */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 10px;\n"
"    margin: 0px 16px 0 16px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgba(149,149,149,75);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::handle::horizontal:hover {\n"
"    background: rgb(85, 170, 255);\n"
"}\n"
"QScrollBar::handle::vertical:hover {\n"
"    background: rgb(85, 170, 255);\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 10px;\n"
"    margin: 16px 0 16px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgba(149,149,149,75);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* CHECKBOX */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/16x16/icons/16x16/cil-check-alt.png);\n"
"}\n"
"\n"
"/* RADIO BUTTON */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* COMBOBOX */\n"
"QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/16x16/icons/16x16/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* SLIDERS */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 9px;\n"
"    height: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 9px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        self.main_body.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setLineWidth(0)
        self.main_body.setObjectName("main_body")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_body)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header1 = QtWidgets.QFrame(self.main_body)
        self.header1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header1.setObjectName("header1")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.header1)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.header_frame = QtWidgets.QFrame(self.header1)
        self.header_frame.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.header_left1 = QtWidgets.QFrame(self.header_frame)
        self.header_left1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_left1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_left1.setObjectName("header_left1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.header_left1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_fileopen = QtWidgets.QPushButton(self.header_left1)
        self.btn_fileopen.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_fileopen.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_fileopen.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_fileopen.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/find/icons/find/五个椭圆_five-ellipses.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_fileopen.setIcon(icon)
        self.btn_fileopen.setObjectName("btn_fileopen")
        self.verticalLayout_4.addWidget(self.btn_fileopen)
        self.horizontalLayout_2.addWidget(self.header_left1, 0, QtCore.Qt.AlignLeft)
        self.header_left = QtWidgets.QFrame(self.header_frame)
        self.header_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_left.setObjectName("header_left")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.header_left)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_header_right_2 = QtWidgets.QLabel(self.header_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_header_right_2.sizePolicy().hasHeightForWidth())
        self.label_header_right_2.setSizePolicy(sizePolicy)
        self.label_header_right_2.setMaximumSize(QtCore.QSize(250, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 29, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 29, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 29, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 29, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 29, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 29, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 29, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 29, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 29, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_header_right_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.label_header_right_2.setFont(font)
        self.label_header_right_2.setObjectName("label_header_right_2")
        self.horizontalLayout_7.addWidget(self.label_header_right_2, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_2.addWidget(self.header_left, 0, QtCore.Qt.AlignLeft)
        self.header_center = QtWidgets.QFrame(self.header_frame)
        self.header_center.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_center.setObjectName("header_center")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.header_center)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_2.addWidget(self.header_center)
        self.header_right = QtWidgets.QFrame(self.header_frame)
        self.header_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_right.setObjectName("header_right")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.header_right)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.minimize_window_button = QtWidgets.QPushButton(self.header_right)
        self.minimize_window_button.setMinimumSize(QtCore.QSize(40, 40))
        self.minimize_window_button.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.minimize_window_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/find/icons/find/减_minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_window_button.setIcon(icon1)
        self.minimize_window_button.setObjectName("minimize_window_button")
        self.horizontalLayout_5.addWidget(self.minimize_window_button)
        self.restore_window_button = QtWidgets.QPushButton(self.header_right)
        self.restore_window_button.setMinimumSize(QtCore.QSize(40, 40))
        self.restore_window_button.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.restore_window_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/find/icons/find/内部扩大_internal-expansion.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restore_window_button.setIcon(icon2)
        self.restore_window_button.setObjectName("restore_window_button")
        self.horizontalLayout_5.addWidget(self.restore_window_button)
        self.close_window_button = QtWidgets.QPushButton(self.header_right)
        self.close_window_button.setMinimumSize(QtCore.QSize(40, 40))
        self.close_window_button.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.close_window_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/find/icons/find/关闭_close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_window_button.setIcon(icon3)
        self.close_window_button.setObjectName("close_window_button")
        self.horizontalLayout_5.addWidget(self.close_window_button)
        self.horizontalLayout_2.addWidget(self.header_right, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_11.addWidget(self.header_frame)
        self.verticalLayout.addWidget(self.header1)
        self.main_body_content = QtWidgets.QFrame(self.main_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body_content.sizePolicy().hasHeightForWidth())
        self.main_body_content.setSizePolicy(sizePolicy)
        self.main_body_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body_content.setLineWidth(0)
        self.main_body_content.setObjectName("main_body_content")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.main_body_content)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_menubar = QtWidgets.QFrame(self.main_body_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_menubar.sizePolicy().hasHeightForWidth())
        self.frame_menubar.setSizePolicy(sizePolicy)
        self.frame_menubar.setStyleSheet("background-color: rgb(39,40, 44);")
        self.frame_menubar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menubar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menubar.setLineWidth(0)
        self.frame_menubar.setObjectName("frame_menubar")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_menubar)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_file_view = QtWidgets.QPushButton(self.frame_menubar)
        self.btn_file_view.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_file_view.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_file_view.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QPushButton { border-left: 3px solid rgb(144, 149, 160); }")
        self.btn_file_view.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/find/icons/find/文件夹_seo-folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_file_view.setIcon(icon4)
        self.btn_file_view.setObjectName("btn_file_view")
        self.verticalLayout_5.addWidget(self.btn_file_view)
        self.btn_datadict = QtWidgets.QPushButton(self.frame_menubar)
        self.btn_datadict.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_datadict.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_datadict.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_datadict.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/find/icons/find/脑图_mind-mapping.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_datadict.setIcon(icon5)
        self.btn_datadict.setObjectName("btn_datadict")
        self.verticalLayout_5.addWidget(self.btn_datadict)
        self.btn_file = QtWidgets.QPushButton(self.frame_menubar)
        self.btn_file.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_file.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_file.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_file.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/find/icons/find/文件夹1_folder-one.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_file.setIcon(icon6)
        self.btn_file.setObjectName("btn_file")
        self.verticalLayout_5.addWidget(self.btn_file)
        self.btn_datamaker = QtWidgets.QPushButton(self.frame_menubar)
        self.btn_datamaker.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_datamaker.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_datamaker.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/find/icons/find/魔方_cube-three.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_datamaker.setIcon(icon7)
        self.btn_datamaker.setObjectName("btn_datamaker")
        self.verticalLayout_5.addWidget(self.btn_datamaker)
        spacerItem = QtWidgets.QSpacerItem(20, 2048, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_5.addItem(spacerItem)
        self.btn_settings = QtWidgets.QPushButton(self.frame_menubar)
        self.btn_settings.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_settings.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_settings.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/find/icons/find/文件设置1_file-settings-one.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_settings.setIcon(icon8)
        self.btn_settings.setObjectName("btn_settings")
        self.verticalLayout_5.addWidget(self.btn_settings)
        self.horizontalLayout_10.addWidget(self.frame_menubar, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.main_interface = QtWidgets.QFrame(self.main_body_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_interface.sizePolicy().hasHeightForWidth())
        self.main_interface.setSizePolicy(sizePolicy)
        self.main_interface.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_interface.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_interface.setLineWidth(0)
        self.main_interface.setObjectName("main_interface")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.main_interface)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.main_interface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setToolTipDuration(5)
        self.splitter.setStyleSheet("QSplitter::handle{\n"
"    border: 1px solid rgb(52, 59, 72);\n"
"    background: rgb(52, 59, 72);\n"
"    width: 1px ;\n"
"    height: 0px;\n"
"}\n"
"QSplitter::handle:hover{/*splitter->handle(1)->setAttribute(Qt::WA_Hover, true);才生效*/\n"
"    border-color: rgb(85, 170, 255);\n"
"    background:  rgb(85, 170, 255);\n"
"    width:5px;\n"
"}\n"
"QSplitter::handle:pressed{\n"
"    border-color: rgb(85, 170, 255);\n"
"    background:  rgb(85, 170, 255);\n"
"    width:5px;\n"
"}")
        self.splitter.setLineWidth(0)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(3)
        self.splitter.setObjectName("splitter")
        self.frame_menulist = QtWidgets.QFrame(self.splitter)
        self.frame_menulist.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_menulist.sizePolicy().hasHeightForWidth())
        self.frame_menulist.setSizePolicy(sizePolicy)
        self.frame_menulist.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_menulist.setMaximumSize(QtCore.QSize(4096, 16777215))
        self.frame_menulist.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(151, 159, 171))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 59, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 59, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 59, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 159, 171))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 59, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 59, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 59, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 59, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 59, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 59, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.frame_menulist.setPalette(palette)
        self.frame_menulist.setStyleSheet("background-color: rgb(52, 59, 72);")
        self.frame_menulist.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menulist.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menulist.setLineWidth(0)
        self.frame_menulist.setObjectName("frame_menulist")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_menulist)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_menustatus = QtWidgets.QLabel(self.frame_menulist)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(152, 160, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 59, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 59, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 59, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 160, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 59, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 59, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 59, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 59, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 59, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 59, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_menustatus.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_menustatus.setFont(font)
        self.label_menustatus.setLineWidth(0)
        self.label_menustatus.setObjectName("label_menustatus")
        self.verticalLayout_7.addWidget(self.label_menustatus)
        self.stackedWidget_menu = QtWidgets.QStackedWidget(self.frame_menulist)
        self.stackedWidget_menu.setStyleSheet("")
        self.stackedWidget_menu.setObjectName("stackedWidget_menu")
        self.page_file_model = QtWidgets.QWidget()
        self.page_file_model.setStyleSheet("QMenu {\n"
"    color:black;\n"
"    background-color:white; \n"
"    border-radius:3px;\n"
"    padding:5px;\n"
"    margin:6px;\n"
"}\n"
"QMenu::item:text { \n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"}\n"
"QMenu::item:selected{ \n"
"    color:#1aa3ff;\n"
"    background-color: #e5f5ff;\n"
"    border-radius:3px;\n"
"}\n"
"QMenu::separator{\n"
"    height:1px;\n"
"    background:#bbbbbb;\n"
"    margin:5px;\n"
"    margin-left:10px;\n"
"    margin-right:10px;\n"
"}")
        self.page_file_model.setObjectName("page_file_model")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_file_model)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_file_dir = QtWidgets.QLabel(self.page_file_model)
        self.label_file_dir.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_file_dir.setFont(font)
        self.label_file_dir.setStyleSheet("color:rgb(200, 200, 200)")
        self.label_file_dir.setLineWidth(0)
        self.label_file_dir.setObjectName("label_file_dir")
        self.verticalLayout_12.addWidget(self.label_file_dir)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_file_filter = QtWidgets.QPushButton(self.page_file_model)
        self.btn_file_filter.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_file_filter.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/find/icons/find/两个椭圆_two-ellipses.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_file_filter.setIcon(icon9)
        self.btn_file_filter.setObjectName("btn_file_filter")
        self.horizontalLayout_8.addWidget(self.btn_file_filter)
        self.lineEdit_file_filter = QtWidgets.QLineEdit(self.page_file_model)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_file_filter.setFont(font)
        self.lineEdit_file_filter.setStyleSheet("\n"
"/* LINE EDIT */\n"
"QLineEdit {\n"
"    background-color: transparent;\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(64, 71, 88);\n"
"    padding-left: 4px;\n"
"    color: rgb(200,200,200);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(85, 170, 255);\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #F5F5F5;\n"
"    border: 1px solid #CCC;\n"
"    padding: 5px;\n"
"    border-radius: 5px; /* 设置圆角 */\n"
"}\n"
"QMenu::item {\n"
"    padding: 2px 20px 2px 20px;\n"
"    border: 1px solid transparent;\n"
"}\n"
"QMenu::item:selected {\n"
"    background-color: #4A90D9;\n"
"    color: #FFF;\n"
"}\n"
"QMenu::separator {\n"
"    height: 1px; /* 分隔线的高度 */\n"
"    background-color: #CCC; /* 分隔线的颜色 */\n"
"    margin: 5px 0px 5px 0px; /* 分隔线的外边距 */\n"
"}")
        self.lineEdit_file_filter.setObjectName("lineEdit_file_filter")
        self.horizontalLayout_8.addWidget(self.lineEdit_file_filter)
        self.btn_file_more_option = QtWidgets.QPushButton(self.page_file_model)
        self.btn_file_more_option.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_file_more_option.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/find/icons/find/魔比斯环_cross-ring-two.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_file_more_option.setIcon(icon10)
        self.btn_file_more_option.setObjectName("btn_file_more_option")
        self.horizontalLayout_8.addWidget(self.btn_file_more_option)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.file_treeView = QtWidgets.QTreeView(self.page_file_model)
        self.file_treeView.setStyleSheet("QTreeView{\n"
"    border: none;\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #F5F5F5;\n"
"    border: 1px solid #CCC;\n"
"    padding: 5px;\n"
"}\n"
"QMenu::item {\n"
"    padding: 2px 20px 2px 20px;\n"
"    border: 1px solid transparent;\n"
"}\n"
"QMenu::item:selected {\n"
"    background-color: #4A90D9;\n"
"    color: #FFF;\n"
"}\n"
"QMenu::separator {\n"
"    height: 1px; /* 分隔线的高度 */\n"
"    background-color: #CCC; /* 分隔线的颜色 */\n"
"    margin: 5px 0px 5px 0px; /* 分隔线的外边距 */\n"
"}")
        self.file_treeView.setLineWidth(0)
        self.file_treeView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.file_treeView.setSortingEnabled(True)
        self.file_treeView.setAnimated(True)
        self.file_treeView.setWordWrap(True)
        self.file_treeView.setHeaderHidden(True)
        self.file_treeView.setObjectName("file_treeView")
        self.file_treeView.header().setVisible(False)
        self.verticalLayout_12.addWidget(self.file_treeView)
        self.stackedWidget_menu.addWidget(self.page_file_model)
        self.page_datamaker = QtWidgets.QWidget()
        self.page_datamaker.setObjectName("page_datamaker")
        self.btn_sxm_maker = QtWidgets.QPushButton(self.page_datamaker)
        self.btn_sxm_maker.setGeometry(QtCore.QRect(20, 30, 75, 23))
        self.btn_sxm_maker.setObjectName("btn_sxm_maker")
        self.btn_3ds_maker = QtWidgets.QPushButton(self.page_datamaker)
        self.btn_3ds_maker.setGeometry(QtCore.QRect(20, 80, 75, 23))
        self.btn_3ds_maker.setObjectName("btn_3ds_maker")
        self.btn_dat_maker = QtWidgets.QPushButton(self.page_datamaker)
        self.btn_dat_maker.setGeometry(QtCore.QRect(20, 140, 75, 23))
        self.btn_dat_maker.setObjectName("btn_dat_maker")
        self.stackedWidget_menu.addWidget(self.page_datamaker)
        self.page_file = QtWidgets.QWidget()
        self.page_file.setEnabled(True)
        self.page_file.setBaseSize(QtCore.QSize(0, 0))
        self.page_file.setObjectName("page_file")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_file)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.page1_layout = QtWidgets.QVBoxLayout()
        self.page1_layout.setSpacing(0)
        self.page1_layout.setObjectName("page1_layout")
        self.treeWidget = QtWidgets.QTreeWidget(self.page_file)
        self.treeWidget.setBaseSize(QtCore.QSize(400, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.treeWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.treeWidget.setFont(font)
        self.treeWidget.setStyleSheet("\n"
"QTreeWidget{\n"
"    background: transparent;\n"
"     border: none\n"
"}\n"
"\n"
"QTreeView::item:selected:active{\n"
"    background: rgb(63, 147, 168);\n"
"}\n"
" \n"
"QTreeView::item:selected:!active {\n"
"    background: rgb(63, 147, 168);\n"
"}\n"
"/*表头*/\n"
"QHeaderView::section{\n"
"text-align:left;\n"
"background:transparent;\n"
"padding:0px;\n"
"margin:0px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.treeWidget.setDragEnabled(True)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setColumnCount(3)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.treeWidget.headerItem().setText(1, "2")
        self.treeWidget.headerItem().setText(2, "3")
        self.treeWidget.header().setVisible(False)
        self.treeWidget.header().setDefaultSectionSize(100)
        self.treeWidget.header().setSortIndicatorShown(False)
        self.page1_layout.addWidget(self.treeWidget)
        self.verticalLayout_10.addLayout(self.page1_layout)
        self.stackedWidget_menu.addWidget(self.page_file)
        self.page_datadict = QtWidgets.QWidget()
        self.page_datadict.setObjectName("page_datadict")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_datadict)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.treeWidget_dict = QtWidgets.QTreeWidget(self.page_datadict)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.treeWidget_dict.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.treeWidget_dict.setFont(font)
        self.treeWidget_dict.setAutoFillBackground(False)
        self.treeWidget_dict.setStyleSheet("QTreeWidget{\n"
"    background: transparent;\n"
"     border: none;\n"
"    color: white\n"
"}\n"
"\n"
"QTreeView::item:selected:active{\n"
"    background: rgb(63, 147, 168);\n"
"}\n"
" \n"
"QTreeView::item:selected:!active {\n"
"    background: rgb(63, 147, 168);\n"
"}\n"
"/*表头*/\n"
"QHeaderView::section{\n"
"    text-align:left;\n"
"    background:transparent;\n"
"    padding:0px;\n"
"    margin:0px;\n"
"    color: rgb(170,170,170);\n"
"    padding-left: 5px;\n"
"    border-left :0.5px solid rgb(170,170,170);\n"
"    border-right:0.5px solid rgb(170,170,170);\n"
"    border-top:0px solid #000;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.treeWidget_dict.setDragEnabled(True)
        self.treeWidget_dict.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.treeWidget_dict.setAlternatingRowColors(False)
        self.treeWidget_dict.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeWidget_dict.setAnimated(True)
        self.treeWidget_dict.setWordWrap(True)
        self.treeWidget_dict.setObjectName("treeWidget_dict")
        self.treeWidget_dict.header().setSortIndicatorShown(False)
        self.verticalLayout_8.addWidget(self.treeWidget_dict)
        self.stackedWidget_menu.addWidget(self.page_datadict)
        self.page_settings = QtWidgets.QWidget()
        self.page_settings.setObjectName("page_settings")
        self.layoutWidget = QtWidgets.QWidget(self.page_settings)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 341, 68))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_temp_dir = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_temp_dir.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_temp_dir.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_temp_dir.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QPushButton { border-left: 3px solid rgb(144, 149, 160); }")
        self.btn_temp_dir.setText("")
        self.btn_temp_dir.setIcon(icon4)
        self.btn_temp_dir.setObjectName("btn_temp_dir")
        self.gridLayout.addWidget(self.btn_temp_dir, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.lineEdit_temp_dir = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_temp_dir.setFont(font)
        self.lineEdit_temp_dir.setStyleSheet("\n"
"/* LINE EDIT */\n"
"QLineEdit {\n"
"    background-color: transparent;\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(64, 71, 88);\n"
"    padding-left: 4px;\n"
"    color: rgb(200,200,200);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(85, 170, 255);\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #F5F5F5;\n"
"    border: 1px solid #CCC;\n"
"    padding: 5px;\n"
"    border-radius: 5px; /* 设置圆角 */\n"
"}\n"
"QMenu::item {\n"
"    padding: 2px 20px 2px 20px;\n"
"    border: 1px solid transparent;\n"
"}\n"
"QMenu::item:selected {\n"
"    background-color: #4A90D9;\n"
"    color: #FFF;\n"
"}\n"
"QMenu::separator {\n"
"    height: 1px; /* 分隔线的高度 */\n"
"    background-color: #CCC; /* 分隔线的颜色 */\n"
"    margin: 5px 0px 5px 0px; /* 分隔线的外边距 */\n"
"}")
        self.lineEdit_temp_dir.setObjectName("lineEdit_temp_dir")
        self.gridLayout.addWidget(self.lineEdit_temp_dir, 0, 1, 1, 1)
        self.stackedWidget_menu.addWidget(self.page_settings)
        self.verticalLayout_7.addWidget(self.stackedWidget_menu)
        self.frame_tab = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_tab.sizePolicy().hasHeightForWidth())
        self.frame_tab.setSizePolicy(sizePolicy)
        self.frame_tab.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tab.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tab.setObjectName("frame_tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_tab)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget::pane\n"
"{\n"
"    border: 0px;\n"
"    background:transparent;\n"
"}\n"
"QTabWidget::tab-bar\n"
"{\n"
"    background:transparent;\n"
"}\n"
" \n"
"QTabBar::tab\n"
" \n"
"{\n"
"    min-width:75px;\n"
"    background:rgb(65, 130, 195);\n"
"}\n"
" \n"
"QTabBar::tab:selected\n"
" \n"
"{\n"
"    color: white;\n"
"    background-color: rgb(45, 49, 59);\n"
"}\n"
" \n"
"QTabBar::tab:!selected\n"
" \n"
"{\n"
"color: rgb(150,150,144);\n"
"background:transparent;\n"
"}\n"
"QTabBar::tab:hover\n"
"{\n"
"color: rgb(36,197,219);\n"
"background:transparent;\n"
"}\n"
"QTabBar::close-button {\n"
"    image:null\n"
"}\n"
"QTabBar::close-button:selected {\n"
"    image: url(:/find/icons/find/关闭_close.svg);\n"
"}\n"
"QTabBar::close-button:selected:hover {\n"
"    image: url(:/find/icons/find/关闭_close.svg);\n"
"    background-color :rgb(120,120,120);\n"
"    border-radius: 3px;\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout_9.addWidget(self.tabWidget)
        self.horizontalLayout_4.addWidget(self.splitter)
        self.horizontalLayout_10.addWidget(self.main_interface)
        self.verticalLayout.addWidget(self.main_body_content)
        self.footer = QtWidgets.QFrame(self.main_body)
        self.footer.setStyleSheet("background-color: rgb(33, 37, 43);\n"
"/*background-color: rgb(0, 122, 204);*/")
        self.footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer.setLineWidth(0)
        self.footer.setObjectName("footer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.foot_left = QtWidgets.QFrame(self.footer)
        self.foot_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.foot_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.foot_left.setLineWidth(0)
        self.foot_left.setObjectName("foot_left")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.foot_left)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.status_label = QtWidgets.QLabel(self.foot_left)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 37, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 37, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 37, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 37, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 37, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 37, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 37, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 37, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 37, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 103, 111, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.status_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.status_label.setFont(font)
        self.status_label.setStyleSheet("color: rgb(240,240,240);")
        self.status_label.setLineWidth(0)
        self.status_label.setObjectName("status_label")
        self.verticalLayout_2.addWidget(self.status_label, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_3.addWidget(self.foot_left)
        self.foot_center = QtWidgets.QFrame(self.footer)
        self.foot_center.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.foot_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.foot_center.setLineWidth(0)
        self.foot_center.setObjectName("foot_center")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.foot_center)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.foot_center)
        self.pushButton_7.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: transparent;\n"
"}")
        self.pushButton_7.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon16/icons/16x16/cil-mood-very-good.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon11)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_3.addWidget(self.foot_center)
        self.frame_size_grip = QtWidgets.QFrame(self.footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_size_grip.sizePolicy().hasHeightForWidth())
        self.frame_size_grip.setSizePolicy(sizePolicy)
        self.frame_size_grip.setMinimumSize(QtCore.QSize(20, 20))
        self.frame_size_grip.setMaximumSize(QtCore.QSize(24, 24))
        self.frame_size_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_size_grip.setLineWidth(0)
        self.frame_size_grip.setObjectName("frame_size_grip")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_size_grip)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.size_grip = QtWidgets.QPushButton(self.frame_size_grip)
        self.size_grip.setMinimumSize(QtCore.QSize(20, 20))
        self.size_grip.setMaximumSize(QtCore.QSize(20, 20))
        self.size_grip.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}")
        self.size_grip.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icon16/icons/16x16/cil-size-grip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.size_grip.setIcon(icon12)
        self.size_grip.setObjectName("size_grip")
        self.verticalLayout_6.addWidget(self.size_grip, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.horizontalLayout_3.addWidget(self.frame_size_grip, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.footer, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.main_body)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget_menu.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_header_right_2.setText(_translate("MainWindow", "Main Window-Base"))
        self.btn_file.setToolTip(_translate("MainWindow", "<html><head/><body><p>File</p></body></html>"))
        self.label_menustatus.setText(_translate("MainWindow", "  File"))
        self.label_file_dir.setText(_translate("MainWindow", "TextLabel"))
        self.lineEdit_file_filter.setPlaceholderText(_translate("MainWindow", "Search"))
        self.btn_sxm_maker.setText(_translate("MainWindow", "sxm"))
        self.btn_3ds_maker.setText(_translate("MainWindow", "3ds"))
        self.btn_dat_maker.setText(_translate("MainWindow", "dat"))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget_dict.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.treeWidget_dict.headerItem().setText(1, _translate("MainWindow", "value/shape"))
        self.lineEdit_temp_dir.setPlaceholderText(_translate("MainWindow", "Search"))
        self.status_label.setText(_translate("MainWindow", "ver 1.0.0"))
# from .icon_rc import *
import icon_rc
